### PR TITLE
add standard issue template

### PR DESCRIPTION
**Pull request by cagix**

### CODE REVIEW

**Comment by AMatutat** [comment]
we should add that in the Dungeon repo as well.

**Comment by cagix** [comment]
yeah, that would probably be helpful.

i added the bug template via "insights > community > add issue template" and it works just fine. next i wanted to do the same for a pull request template, but there you have to create it manually (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository). but somehow that doesn't seem to work :/ 

in addition, i've now seen on another page (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) that the markdown template created by the configurator seems to be deprecated and you should create a yaml template. hmm.

**Comment by cagix** [comment]
okay, moving the pr template one folder up in the hierarchy solved the problem :)

**Comment by cagix** [comment]
@AMatutat strangly there is no "insights > community" in the dungeon repo. maybe this is due to it's fork nature? perhaps we should de-fork this repo as it is our main pmdungeon repo now? however, this would involve github support.

**Pull request merged**
